"""
Report generation module for SDRLab.
Assembles simulation sweeps, config parameters, and performance data into a formatted Markdown report.
References and links visualizations generated by the SDRLabVisualizer.
"""

import os
from pathlib import Path
from typing import Dict, Any, List
import pandas as pd

from sdrlab.logger import SDRLabLogger

logger = SDRLabLogger.get_logger()


class SimulationReporter:
    """
    Assembles simulation results and links output plots into a final Markdown report.
    Saved to outputs/reports/.
    """

    def __init__(self, output_dir: str = "outputs") -> None:
        self.output_dir = Path(output_dir)
        self.reports_dir = self.output_dir / "reports"
        self.csv_dir = self.output_dir / "csv"
        
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.csv_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(
        self,
        config: Any,
        results_df: pd.DataFrame,
        generated_figures: Dict[str, List[Dict[str, Any]]],  # Mod -> List of Dict containing {'snr': X, 'constellation': Y, 'waveform': Z, 'psd': W}
        ber_curve_path: str,
        filename: str = "simulation_report.md",
    ) -> str:
        """
        Assembles all simulation results and assets into a Markdown report.
        
        Args:
            config: An instance of SimulationConfig.
            results_df: Pandas DataFrame containing consolidated sweep metrics.
            generated_figures: Dict containing paths to individual run plots.
            ber_curve_path: Path to the generated BER sweep chart.
            filename: Output markdown filename.
            
        Returns:
            str: Path to the generated report file.
        """
        # Save results DataFrame to CSV first
        csv_path = self.csv_dir / "sweep_results.csv"
        results_df.to_csv(csv_path, index=False)
        logger.info(f"Sweep results exported to CSV: {csv_path}")

        reports_dir_abs = self.reports_dir.resolve()

        # Construct Markdown text
        md = []
        md.append("# SDRLab Simulation Performance Report")
        md.append("")
        md.append("Automated performance validation report for modular wireless communication simulation.")
        md.append("")
        
        # 1. Configuration Section
        md.append("## 1. Simulation Configurations")
        md.append("")
        md.append("| Parameter | Configured Value | Description |")
        md.append("|---|---|---|")
        md.append(f"| **Engine Mode** | `{config.engine}` | Simulation execution engine backend |")
        md.append(f"| **Bits Simulated** | {config.num_bits:,} | Total bit budget per modulation run |")
        md.append(f"| **Sample Rate** | {config.sample_rate:,} Hz | Sample rate ($F_s$) |")
        md.append(f"| **Samples Per Symbol** | {config.sps} | Upsampling ratio ($SPS$) |")
        md.append(f"| **Excess BW (Alpha)** | {config.excess_bw} | RRC filter roll-off factor |")
        md.append(f"| **Filter Span** | {config.filter_span} symbols | RRC filter span length |")
        md.append(f"| **Frequency Offset** | {config.channel_impairments.cfo_hz} Hz | Carrier Frequency Offset (CFO) |")
        md.append(f"| **Phase Noise Var** | {config.channel_impairments.phase_noise_var} | Channel phase noise variance |")
        md.append(f"| **Multipath Taps** | `{config.channel_impairments.multipath_taps}` | Multipath channel impulse response taps |")
        md.append("")

        # 2. Performance Summary Table
        md.append("## 2. Performance Metrics Sweep")
        md.append("")
        md.append("The table below details empirical measurements and calculations from the simulation sweep:")
        md.append("")
        
        # Convert DataFrame to Markdown table formatting
        md_table = results_df.to_markdown(index=False)
        md.append(md_table)
        md.append("")
        
        # 3. Visualizations Sweep
        md.append("## 3. BER Performance Curves")
        md.append("")
        md.append("Bit Error Rate (BER) vs energy-per-bit to noise power spectral density (Eb/N0) comparison:")
        md.append("")
        
        # Get relative path for BER curve from report location
        rel_ber_curve = os.path.relpath(ber_curve_path, reports_dir_abs) if Path(ber_curve_path).is_absolute() else Path("../plots/ber_vs_snr.png")
        # Format path using forward slashes for cross-platform markdown compatibility
        rel_ber_curve_str = str(rel_ber_curve).replace("\\", "/")
        md.append(f"![BER Sweep Curve]({rel_ber_curve_str})")
        md.append("")

        # 4. Detailed Figures by Modulation
        md.append("## 4. Waveform & Constellation Analysis")
        md.append("")
        
        for mod, runs in generated_figures.items():
            md.append(f"### {mod} Analysis Figures")
            md.append("")
            for run in runs:
                snr = run["snr"]
                md.append(f"#### SNR = {snr} dB")
                md.append("")
                
                # Relative paths
                c_path = run.get("constellation")
                w_path = run.get("waveform")
                p_path = run.get("psd")
                
                # Build side-by-side or block listing for figures
                if c_path and Path(c_path).exists():
                    rel_c = os.path.relpath(c_path, reports_dir_abs) if Path(c_path).is_absolute() else Path(c_path)
                    rel_c_str = str(rel_c).replace("\\", "/")
                    md.append(f"- **Constellation Comparison** (Ideal vs Noisy vs Recovered):")
                    md.append(f"  ![{mod} Constellation SNR {snr}]({rel_c_str})")
                    md.append("")
                
                if w_path and Path(w_path).exists():
                    rel_w = os.path.relpath(w_path, reports_dir_abs) if Path(w_path).is_absolute() else Path(w_path)
                    rel_w_str = str(rel_w).replace("\\", "/")
                    md.append(f"- **Waveform Time Domain** (Tx vs Received Noisy):")
                    md.append(f"  ![{mod} Waveform SNR {snr}]({rel_w_str})")
                    md.append("")
                    
                if p_path and Path(p_path).exists():
                    rel_p = os.path.relpath(p_path, reports_dir_abs) if Path(p_path).is_absolute() else Path(p_path)
                    rel_p_str = str(rel_p).replace("\\", "/")
                    md.append(f"- **Power Spectral Density** (PSD):")
                    md.append(f"  ![{mod} PSD SNR {snr}]({rel_p_str})")
                    md.append("")

        # Write to report file
        report_file = self.reports_dir / filename
        with open(report_file, "w", encoding="utf-8") as f:
            f.write("\n".join(md))

        logger.info(f"Performance report generated successfully: {report_file}")
        return str(report_file.resolve())
